# -*- coding: utf-8 -*-
"""生成并导入内置基础词库 → SQLite。

纯本地，无 AI。每个词条:
  (word, phonetic, meaning, pos, theme, [搭配(phrase,meaning,example)], [例句(sentence,translation)])

首版覆盖阶段0常用主题，供"贴词自动匹配"跑通。后续可外部扩充。
"""
import json, os, sqlite3, sys
sys.path.insert(0, os.path.dirname(__file__))
from db import get_conn, ts, init_db

# 结构: 词条三元组列表
# V = word, phonetic, meaning, pos, theme, collocs, examples
V = [
    # ===== 家庭与人际 (theme 家庭/人际) =====
    ("family","家庭","名词","家庭",
     [("my family","我的家庭","I love my family.")],
     [("There are four people in my family.","我家有四口人。"),
      ("My family has dinner together every evening.","我家每晚一起吃晚饭。")]),
    ("mother","母亲","名词","家庭",
     [("my mother","我的母亲","My mother cooks well.")],
     [("My mother works in a hospital.","我妈妈在一家医院工作。"),
      ("I often help my mother at home.","我经常在家帮妈妈。")]),
    ("father","父亲","名词","家庭",
     [("my father","我的父亲","My father reads the newspaper.")],
     [("My father drives me to school.","我爸爸开车送我上学。"),
      ("His father is a kind teacher.","他爸爸是一位和善的老师。")]),
    ("brother","兄弟","名词","家庭",
     [("my little brother","我的弟弟","My little brother likes toys.")],
     [("My brother plays football on weekends.","我哥哥周末踢足球。"),
      ("She has two younger brothers.","她有两个弟弟。")]),
    ("sister","姐妹","名词","家庭",
     [("my older sister","我的姐姐","My older sister helps me study.")],
     [("My sister enjoys singing.","我姐姐喜欢唱歌。"),
      ("He has a lovely sister.","他有一个可爱的妹妹。")]),
    ("parent","父母","名词","家庭",
     [("my parents","我的父母","My parents are kind.")],
     [("My parents take care of me.","我父母照顾我。"),
      ("She lives with her parents.","她和父母住在一起。")]),
    ("friend","朋友","名词","人际",
     [("make friends","交朋友","It is easy to make friends here."),
      ("best friend","最好的朋友","She is my best friend.")],
     [("I go to the park with my friends on Sunday.","我周日和朋友去公园。"),
      ("My best friend lives next door to me.","我最好的朋友住我隔壁。")]),
    ("people","人们","名词","人际",
     [("many people","许多人","Many people like coffee.")],
     [("People in this city are very friendly.","这座城市的人很友好。"),
      ("Young people love to travel.","年轻人喜欢旅行。")]),
    ("name","名字","名词","人际",
     [("my name","我的名字","My name is Tom.")],
     [("What is your name?","你叫什么名字？"),
      ("Please write your name on the paper.","请把名字写在纸上。")]),
    ("meet","遇见，见面","动词","人际",
     [("meet friends","见朋友","I meet friends after class."),
      ("nice to meet you","很高兴见到你","Nice to meet you!")],
     [("I often meet my teacher at the library.","我常在图书馆遇见老师。"),
      ("Let's meet at the station at six.","我们六点在车站见。")]),
    ("love","爱，喜欢","动词","家庭",
     [("love doing","喜欢做某事","I love playing basketball.")],
     [("I love my family very much.","我非常爱我的家人。"),
      ("She loves to read before going to bed.","她喜欢睡前读书。")]),
    ("family member","家庭成员","名词","家庭",
     [("all the family members","所有家庭成员","We invited all the family members.")],
     [("Every family member has a duty.","每个家庭成员都有责任。"),
      ("I talked with my family members last night.","我昨晚和家人聊天了。")]),

    # ===== 工作与日常 =====
    ("work","工作","动词","工作",
     [("go to work","去上班","I go to work by bus."),
      ("at work","在工作","He is at work now.")],
     [("I usually go to work at eight in the morning.","我通常早上八点去上班。"),
      ("She works in a big company.","她在一家大公司工作。")]),
    ("job","工作，职业","名词","工作",
     [("get a job","找到工作","She wants to get a job."),
      ("do a good job","做得好","You did a good job!")],
     [("His job is to answer the phone.","他的工作是接电话。"),
      ("Finding a good job takes time and effort.","找一份好工作需要时间和努力。")]),
    ("study","学习","动词","工作",
     [("study English","学英语","I study English every day."),
      ("study hard","努力学习","He studies hard.")],
     [("I usually study English after dinner because I have more time at night.","我通常在晚饭后学英语，因为晚上时间更多。"),
      ("She studies at a famous university.","她在一所著名大学学习。")]),
    ("office","办公室","名词","工作",
     [("in the office","在办公室","He is in the office.")],
     [("I go to the office every weekday.","我每个工作日都去办公室。"),
      ("Our meeting is in the office tomorrow.","我们明天在办公室开会。")]),
    ("start","开始","动词","日常",
     [("start work","开始工作","We start work at nine."),
      ("start to do","开始做","It started to rain.")],
     [("I start my work at nine o'clock.","我九点开始工作。"),
      ("The movie starts at seven in the evening.","电影晚上七点开始。")]),
    ("finish","完成","动词","日常",
     [("finish work","完成工作","I finish work at five."),
      ("finish doing","做完某事","I finished reading the book.")],
     [("I finish work at five thirty in the afternoon.","我下午五点半完成工作。"),
      ("Have you finished your homework yet?","你完成作业了吗？")]),
    ("morning","早晨","名词","日常",
     [("in the morning","在早上","I run in the morning.")],
     [("I get up early in the morning.","我早上起得很早。"),
      ("We have a meeting on Monday morning.","我们周一早上开会。")]),
    ("usually","通常","副词","日常",
     [("usually do","通常做","I usually have tea.")],
     [("I usually study English after dinner because I have more time at night.","我通常在晚饭后学英语，因为晚上时间更多。"),
      ("I usually go to the gym after work, but I sometimes go home when I'm tired.","我通常下班后去健身房，但有时累了就直接回家。")]),
    ("always","总是","副词","日常",
     [("always do","总是做","He always helps others.")],
     [("I always brush my teeth before going to bed.","我睡前总是刷牙。"),
      ("She always arrives at school on time.","她总是准时到校。")]),
    ("sometimes","有时","副词","日常",
     [("sometimes do","有时做","I sometimes cook dinner.")],
     [("I sometimes watch TV in the evening.","我有时晚上看电视。"),
      ("He sometimes walks to school when it is sunny.","天晴时他有时走路去学校。")]),
    ("never","从不","副词","日常",
     [("never do","从不做","I never smoke.")],
     [("I never get up late on weekdays.","我工作日从不晚起。"),
      ("She never forgets her homework.","她从不忘记作业。")]),
    ("early","早的，早地","形容词","日常",
     [("get up early","早起","I get up early.")],
     [("I get up early to catch the first bus.","我早起赶第一班公交。"),
      ("It is good for health to go to bed early.","早睡有益健康。")]),
    ("late","晚的，迟的","形容词","日常",
     [("be late for","迟到","Don't be late for class.")],
     [("He was late for the meeting this morning.","他今天早上开会迟到了。"),
      ("I go to bed late on Friday nights.","我周五晚上睡得很晚。")]),
    ("homework","家庭作业","名词","日常",
     [("do homework","做作业","I do my homework after school.")],
     [("I usually do my homework in the evening.","我通常在晚上做作业。"),
      ("She finished her homework before dinner.","她晚饭前做完了作业。")]),
    ("busy","忙碌的","形容词","日常",
     [("be busy with","忙于","She is busy with work.")],
     [("I am very busy this week.","我这周非常忙。"),
      ("He is busy preparing for the exam.","他忙着准备考试。")]),

    # ===== 爱好与休闲 =====
    ("hobby","爱好","名词","爱好",
     [("a hobby","一个爱好","Reading is a good hobby.")],
     [("My hobby is collecting old coins.","我的爱好是收集旧硬币。"),
      ("Everyone needs a relaxing hobby.","每个人都需要一个放松的爱好。")]),
    ("like","喜欢","动词","爱好",
     [("like doing","喜欢做","I like reading."),
      ("like to do","喜欢去做","I like to travel.")],
     [("I like listening to music in my free time.","我喜欢在空闲时听音乐。"),
      ("She likes to draw pictures of flowers.","她喜欢画花。")]),
    ("enjoy","享受，喜欢","动词","爱好",
     [("enjoy doing","享受做某事","I enjoy playing chess.")],
     [("I enjoy reading novels on rainy days.","我喜欢在雨天读小说。"),
      ("They enjoy spending time with good friends.","他们喜欢和好朋友待在一起。")]),
    ("hate","讨厌","动词","爱好",
     [("hate doing","讨厌做某事","I hate getting up late.")],
     [("I hate waiting for the bus in winter.","我讨厌冬天等公交。"),
      ("She hates losing at any game.","她讨厌在任何比赛中输。")]),
    ("swim","游泳","动词","爱好",
     [("go swimming","去游泳","We go swimming on Sundays.")],
     [("I swim twice a week in the summer.","夏天我一周游两次泳。"),
      ("He learned to swim at the age of six.","他六岁时学会了游泳。")]),
    ("music","音乐","名词","爱好",
     [("listen to music","听音乐","I listen to music when I study.")],
     [("I listen to music on my way to work.","我上班路上听音乐。"),
      ("She plays soft music in her room.","她在房间放轻柔的音乐。")]),
    ("movie","电影","名词","爱好",
     [("watch a movie","看电影","Let's watch a movie tonight.")],
     [("I watch a movie with my friends on Friday night.","我周五晚上和朋友看电影。"),
      ("This movie is full of fun.","这部电影充满乐趣。")]),
    ("game","游戏，比赛","名词","爱好",
     [("play games","玩游戏","Children like to play games.")],
     [("We play board games together at the weekend.","我们周末一起玩桌游。"),
      ("He won the football game yesterday.","他昨天赢了足球赛。")]),
    ("read","阅读","动词","爱好",
     [("read books","读书","I read books before bed."),
      ("read a newspaper","看报纸","He reads the newspaper daily.")],
     [("I read English books to improve my vocabulary.","我读英语书来提高词汇量。"),
      ("She reads for half an hour every night.","她每晚读半小时书。")]),
    ("sport","运动","名词","爱好",
     [("do sport","做运动","I do sport every day."),
      ("play sports","做运动","Kids love to play sports.")],
     [("Football is my favourite sport.","足球是我最喜欢的运动。"),
      ("Doing sport every day keeps you healthy.","每天做运动让你保持健康。")]),
    ("free","空闲的，免费的","形容词","爱好",
     [("free time","空闲时间","I read in my free time."),
      ("be free","有空","I am free this afternoon.")],
     [("I often paint pictures in my free time.","我常在空闲时间画画。"),
      ("Are you free to play basketball this weekend?","你这周末有空打篮球吗？")]),
    ("draw","画画","动词","爱好",
     [("draw a picture","画一幅画","She can draw a picture.")],
     [("I like to draw pictures of nature.","我喜欢画自然风景。"),
      ("He draws cartoons for fun after school.","他放学后画漫画玩。")]),
    ("dance","跳舞","动词","爱好",
     [("dance to music","跟着音乐跳舞","We dance to the music.")],
     [("She loves to dance at parties.","她喜欢在聚会上跳舞。"),
      ("They danced together all night.","他们整晚一起跳舞。")]),
    ("sing","唱歌","动词","爱好",
     [("sing a song","唱一首歌","She sang a song.")],
     [("I enjoy singing in the shower.","我喜欢在淋浴时唱歌。"),
      ("She sings very well on stage.","她在舞台上唱得很好。")]),
    ("interesting","有趣的","形容词","爱好",
     [("an interesting book","一本有趣的书","This is an interesting book.")],
     [("The movie is really interesting.","这部电影真的很有趣。"),
      ("I read an interesting article about travel.","我读了一篇关于旅行的有趣文章。")]),
    ("fun","乐趣，有趣的","名词","爱好",
     [("have fun","玩得开心","We had fun yesterday."),
      ("a fun game","一个有趣的游戏","This is a fun game.")],
     [("We had a lot of fun at the party.","我们在聚会上玩得很开心。"),
      ("Playing with friends is great fun.","和朋友一起玩很有趣。")]),
    ("weekend","周末","名词","爱好",
     [("at the weekend","在周末","I relax at the weekend."),
      ("last weekend","上个周末","I went hiking last weekend.")],
     [("I usually visit my grandparents at the weekend.","我通常在周末看望祖父母。"),
      ("We are going camping this weekend.","我们这个周末要去露营。")]),
    ("together","一起","副词","爱好",
     [("do together","一起做","We study together.")],
     [("My friends and I often play football together.","我和朋友们经常一起踢足球。"),
      ("The whole family cooks together on Sundays.","全家人周日在厨房一起做饭。")]),
    ("relax","放松","动词","爱好",
     [("relax at home","在家放松","I relax at home.")],
     [("I like to relax at home after a busy week.","忙碌一周后我喜欢在家放松。"),
      ("Listening to music helps me relax.","听音乐帮助我放松。")]),
    ("exercise","锻炼","名词/动词","爱好",
     [("do exercise","做锻炼","I do exercise daily.")],
     [("Exercise keeps my body strong.","锻炼让我身体强壮。"),
      ("I exercise in the park every morning.","我每天早上在公园锻炼。")]),
    ("collect","收集","动词","爱好",
     [("collect stamps","集邮","He collects stamps.")],
     [("I collect stickers from different countries.","我收集不同国家的贴纸。"),
      ("She has collected many postcards over the years.","这些年她收集了许多明信片。")]),

    # ===== 交通与出行 =====
    ("bus","公共汽车","名词","交通",
     [("by bus","乘公交","I go to work by bus."),
      ("take a bus","坐公交","Let's take a bus.")],
     [("I take the bus to school every day.","我每天坐公交上学。"),
      ("The bus to the city leaves every half hour.","去市里的公交每半小时一班。")]),
    ("car","小汽车","名词","交通",
     [("by car","乘汽车","We travel by car."),
      ("drive a car","开车","He drives a red car.")],
     [("My father drives his car to work.","我爸爸开车上班。"),
      ("This new car uses less fuel.","这辆新车更省油。")]),
    ("train","火车","名词","交通",
     [("by train","乘火车","She goes to Beijing by train."),
      ("catch a train","赶火车","We must catch the train.")],
     [("I usually travel to work by train.","我通常乘火车上班。"),
      ("The train to Shanghai leaves at ten.","去上海的火车十点出发。")]),
    ("station","车站","名词","交通",
     [("at the station","在车站","I wait at the station.")],
     [("We meet at the train station at eight.","我们八点在火车站见面。"),
      ("The station is within walking distance.","车站步行可达。")]),
    ("travel","旅行","动词/名词","交通",
     [("travel abroad","出国旅行","I want to travel abroad."),
      ("go traveling","去旅行","They go traveling in summer.")],
     [("I want to travel around the world one day.","我想有一天环游世界。"),
      ("She loves to travel to new places.","她喜欢去新地方旅行。")]),
    ("drive","开车","动词","交通",
     [("drive a car","开车","He drives carefully."),
      ("drive to work","开车上班","She drives to work.")],
     [("I drive to work when it rains.","下雨时我开车上班。"),
      ("Learning to drive takes a lot of practice.","学开车需要大量练习。")]),
    ("road","道路","名词","交通",
     [("on the road","在路上","There are many cars on the road.")],
     [("The road to the station is very busy in the morning.","去车站的路早上很堵。"),
      ("Be careful when you cross the road.","过马路时要小心。")]),
    ("walk","走路","动词","交通",
     [("walk to school","走路去学校","I walk to school."),
      ("take a walk","散步","Let's take a walk.")],
     [("I usually walk to school because it is near.","我通常走路上学因为很近。"),
      ("We take a walk in the park after dinner.","我们晚饭后在公园散步。")]),
    ("ride","骑","动词","交通",
     [("ride a bike","骑自行车","I ride a bike to work."),
      ("go for a ride","去兜风","Let's go for a ride.")],
     [("I ride my bike to school when the weather is nice.","天气好时我骑自行车上学。"),
      ("She is learning to ride a horse.","她在学骑马。")]),
    ("bike","自行车","名词","交通",
     [("by bike","骑自行车","He goes to work by bike.")],
     [("Riding a bike is good for the environment.","骑自行车对环境有益。"),
      ("My bike is outside the school.","我的自行车在学校外面。")]),
    ("plane","飞机","名词","交通",
     [("by plane","乘飞机","They travel by plane.")],
     [("We go to Hainan by plane in winter.","我们冬天坐飞机去海南。"),
      ("The plane takes off at noon.","飞机中午起飞。")]),
    ("airport","机场","名词","交通",
     [("at the airport","在机场","We waited at the airport.")],
     [("I arrived at the airport two hours early.","我提前两小时到机场。"),
      ("The airport is far from the city centre.","机场离市中心很远。")]),
    ("ticket","票","名词","交通",
     [("buy a ticket","买票","I need to buy a ticket."),
      ("a train ticket","火车票","I booked a train ticket online.")],
     [("I bought a train ticket for tomorrow.","我买了一张明天的火车票。"),
      ("How much is the ticket to the museum?","去博物馆的票多少钱？")]),
    ("map","地图","名词","交通",
     [("read a map","看地图","He is reading a map.")],
     [("I use a map when I travel to a new city.","我去新城市时用地图。"),
      ("Look at the map to find the way.","看地图找路。")]),
    ("direction","方向","名词","交通",
     [("ask for directions","问路","I asked for directions."),
      ("in the right direction","朝正确方向","We are going in the right direction.")],
     [("Can you tell me the direction to the bank?","你能告诉我去银行的方向吗？"),
      ("He walked in the wrong direction.","他走错了方向。")]),
    ("traffic","交通，车流","名词","交通",
     [("traffic jam","交通堵塞","We were stuck in a traffic jam."),
      ("heavy traffic","繁忙的交通","There is heavy traffic now.")],
     [("I was late because of heavy traffic.","我因交通拥堵迟到了。"),
      ("The traffic is light in the morning.","早上的车流较少。")]),

    # ===== 地点与城市 =====
    ("city","城市","名词","地点",
     [("in the city","在城市里","He lives in the city.")],
     [("Beijing is a big and modern city.","北京是一座又大又现代的城市。"),
      ("I was born in this small city.","我出生在这座小城。")]),
    ("park","公园","名词","地点",
     [("in the park","在公园","We played in the park.")],
     [("There is a beautiful park near my home.","我家附近有一个美丽的公园。"),
      ("People jog in the park every morning.","人们每天早上在公园慢跑。")]),
    ("school","学校","名词","地点",
     [("go to school","去上学","I go to school at seven."),
      ("at school","在学校","He is at school now.")],
     [("I go to school by bike every day.","我每天骑车上学。"),
      ("Our school has a large library.","我们学校有一个大图书馆。")]),
    ("hospital","医院","名词","地点",
     [("in hospital","住院","He is in hospital.")],
     [("She works as a nurse in the hospital.","她在医院做护士。"),
      ("The hospital is open twenty-four hours.","这家医院24小时营业。")]),
    ("bank","银行","名词","地点",
     [("at the bank","在银行","I went to the bank.")],
     [("I need to go to the bank this afternoon.","我今天下午要去银行。"),
      ("The bank is on the corner of the street.","银行在街角。")]),
    ("shop","商店","名词","地点",
     [("go shopping","去购物","We go shopping on Saturdays.")],
     [("There is a small shop next to my home.","我家旁边有一家小店。"),
      ("She opened a flower shop last year.","她去年开了一家花店。")]),
    ("restaurant","餐厅","名词","地点",
     [("at a restaurant","在餐厅","We ate at a restaurant.")],
     [("We had dinner at a Chinese restaurant.","我们在一家中餐馆吃晚饭。"),
      ("This restaurant serves delicious food.","这家餐厅供应美味的食物。")]),
    ("library","图书馆","名词","地点",
     [("in the library","在图书馆","I study in the library.")],
     [("I borrow books from the library every week.","我每周从图书馆借书。"),
      ("The library is quiet and clean.","图书馆安静又干净。")]),
    ("supermarket","超市","名词","地点",
     [("at the supermarket","在超市","I buy food at the supermarket.")],
     [("I do the weekly shopping at the supermarket.","我在超市买每周的东西。"),
      ("The supermarket is near the bus station.","超市在公交站附近。")]),
    ("street","街道","名词","地点",
     [("on the street","在街上","There are many cars on the street.")],
     [("I walk along the main street every day.","我每天沿主街走。"),
      ("Their house is on a quiet street.","他们的房子在一条安静的街上。")]),
    ("home","家","名词","地点",
     [("go home","回家","I go home after school."),
      ("at home","在家","She stays at home.")],
     [("I usually go home at five thirty.","我通常五点半回家。"),
      ("There is no place like home.","没有什么地方比得上家。")]),
    ("place","地方","名词","地点",
     [("a good place","一个好地方","This is a good place to rest.")],
     [("This park is a great place to relax.","这个公园是个放松的好地方。"),
      ("I know a quiet place to read.","我知道一个安静的地方读书。")]),
    ("near","在…附近","介词","地点",
     [("near my home","我家附近","The school is near my home.")],
     [("There is a market near my house.","我家附近有一个市场。"),
      ("He lives near the station.","他住在车站附近。")]),
    ("far","远的","形容词","地点",
     [("far from","离…远","The shop is far from here.")],
     [("My school is far from my home, so I take a bus.","学校离家远，所以我坐公交。"),
      ("How far is it to the airport?","到机场有多远？")]),

    # ===== 时间与生活 =====
    ("time","时间","名词","时间",
     [("free time","空闲时间","I have no free time today."),
      ("on time","准时","Please be on time.")],
     [("I don't have enough time to finish it.","我没有足够时间完成它。"),
      ("What time do you get up?","你几点起床？")]),
    ("today","今天","名词/副词","时间",
     [("today is","今天是","Today is Monday.")] ,
     [("It is sunny today.","今天天气晴朗。"),
      ("We have a test today.","我们今天有考试。")]),
    ("yesterday","昨天","名词/副词","时间",
     [("yesterday evening","昨天晚上","I watched TV yesterday evening.")],
     [("I went to the zoo yesterday.","我昨天去了动物园。"),
      ("She finished her work yesterday.","她昨天完成了工作。")]),
    ("tomorrow","明天","名词/副词","时间",
     [("tomorrow morning","明天早上","I will call you tomorrow morning.")],
     [("We are going to the beach tomorrow.","我们明天去海滩。"),
      ("I will meet you tomorrow afternoon.","我明天下午见你。")]),
    ("week","星期，周","名词","时间",
     [("this week","这周","I am busy this week.")],
     [("I have three English classes this week.","这周我有三节英语课。"),
      ("She works five days a week.","她一周工作五天。")]),
    ("month","月","名词","时间",
     [("this month","这个月","I read two books this month.")],
     [("We travel abroad once a month.","我们一个月出国旅行一次。"),
      ("The project will finish next month.","这个项目下月完成。")]),
    ("year","年","名词","时间",
     [("last year","去年","I moved here last year.")],
     [("I plan to visit my uncle next year.","我计划明年拜访叔叔。"),
      ("She has studied English for three years.","她学英语三年了。")]),
    ("hour","小时","名词","时间",
     [("an hour","一小时","I waited for an hour.")],
     [("It takes an hour to get there by bus.","坐公交到那里要一个小时。"),
      ("I study English for two hours every day.","我每天学两小时英语。")]),
    ("o'clock","点钟","名词","时间",
     [("at nine o'clock","在九点","I start at nine o'clock.")],
     [("We have lunch at twelve o'clock.","我们十二点吃午饭。"),
      ("The shop opens at nine o'clock.","商店九点开门。")]),
    ("plan","计划","名词/动词","时间",
     [("make a plan","制定计划","Let's make a plan."),
      ("plan to do","计划做","I plan to travel.")],
     [("We are making a plan for the weekend.","我们在制定周末计划。"),
      ("I plan to improve my English this year.","我计划今年提高英语。")]),
    ("future","未来","名词","时间",
     [("in the future","在未来","I want to be a doctor in the future.")],
     [("In the future, I hope to live by the sea.","未来我希望住在海边。"),
      ("We can't predict the future.","我们无法预测未来。")]),
    ("minute","分钟","名词","时间",
     [("a few minutes","几分钟","Wait a few minutes.")],
     [("I'll be back in a few minutes.","我几分钟后回来。"),
      ("The bus comes every ten minutes.","公交车每十分钟一班。")]),

    # ===== 食物与饮食 =====
    ("food","食物","名词","食物",
     [("healthy food","健康食物","I eat healthy food.")],
     [("Chinese food is popular around the world.","中餐在世界各地都很受欢迎。"),
      ("We bought some food for the picnic.","我们买了一些野餐的食物。")]),
    ("breakfast","早餐","名词","食物",
     [("have breakfast","吃早餐","I have breakfast at seven.")],
     [("I usually have breakfast at home before I go to work.","我通常上班前在家吃早餐。"),
      ("A good breakfast gives you energy.","一顿好的早餐给你能量。")]),
    ("lunch","午餐","名词","食物",
     [("have lunch","吃午餐","We have lunch at twelve.")],
     [("I often have lunch at the school canteen.","我常在学校食堂吃午餐。"),
      ("Let's have lunch together tomorrow.","我们明天一起吃午饭吧。")]),
    ("dinner","晚餐","名词","食物",
     [("have dinner","吃晚餐","They have dinner at six.")],
     [("I usually study English after dinner because I have more time at night.","我通常在晚饭后学英语，因为晚上时间更多。"),
      ("We had a big dinner for my birthday.","我们为我的生日吃了一顿大餐。")]),
    ("rice","米饭","名词","食物",
     [("a bowl of rice","一碗米饭","He ate a bowl of rice.")],
     [("I eat rice with my meals every day.","我每天吃饭都吃米饭。"),
      ("Fried rice is my favourite dish.","炒饭是我最喜欢的菜。")]),
    ("noodle","面条","名词","食物",
     [("a bowl of noodles","一碗面","She ordered a bowl of noodles.")],
     [("I like beef noodles for breakfast.","我早餐喜欢吃牛肉面。"),
      ("We had noodles in the restaurant.","我们在餐厅吃了面条。")]),
    ("fruit","水果","名词","食物",
     [("fresh fruit","新鲜水果","I eat fresh fruit.")],
     [("I eat fruit after every meal.","我每顿饭后吃水果。"),
      ("Apples and bananas are common fruits.","苹果和香蕉是常见水果。")]),
    ("apple","苹果","名词","食物",
     [("an apple","一个苹果","I have an apple a day.")],
     [("An apple a day keeps the doctor away.","一天一个苹果，医生远离我。"),
      ("She picked an apple from the tree.","她从树上摘了一个苹果。")]),
    ("vegetable","蔬菜","名词","食物",
     [("green vegetables","绿色蔬菜","Eat more green vegetables.")],
     [("Vegetables are good for your health.","蔬菜对你的健康有益。"),
      ("I grow vegetables in my garden.","我在花园里种蔬菜。")]),
    ("water","水","名词","食物",
     [("a glass of water","一杯水","I drank a glass of water."),
      ("drink water","喝水","Drink more water.")],
     [("Drinking enough water is important.","喝足够的水很重要。"),
      ("I drink water after running.","我跑步后喝水。")]),
    ("tea","茶","名词","食物",
     [("a cup of tea","一杯茶","I'd like a cup of tea.")],
     [("I drink a cup of tea in the afternoon.","我下午喝一杯茶。"),
      ("Green tea is good for you.","绿茶对你有好处。")]),
    ("milk","牛奶","名词","食物",
     [("a glass of milk","一杯牛奶","He drank a glass of milk.")],
     [("I have a glass of milk before bed.","我睡前喝一杯牛奶。"),
      ("Milk is rich in calcium.","牛奶富含钙。")]),
    ("delicious","美味的","形容词","食物",
     [("delicious food","美味的食物","The cake is delicious.")],
     [("This soup is really delicious.","这汤真的很美味。"),
      ("My mother makes delicious cookies.","我妈妈做的饼干很好吃。")]),
    ("hungry","饥饿的","形容词","食物",
     [("be hungry","饿了","I am hungry.")],
     [("I was hungry after the long walk.","走了很长一段路后我饿了。"),
      ("Are you hungry? Let's eat something.","你饿了吗？我们吃点东西吧。")]),
    ("thirsty","口渴的","形容词","食物",
     [("be thirsty","口渴","I am thirsty.")],
     [("Running in the sun made me thirsty.","在太阳下跑步让我口渴。"),
      ("If you are thirsty, drink some water.","如果你渴了，就喝点水。")]),
    ("cook","烹饪，做饭","动词","食物",
     [("cook dinner","做晚饭","I cook dinner at six."),
      ("cook food","做饭","She cooks healthy food.")],
     [("I like to cook for my family on Sundays.","我喜欢周日为家人做饭。"),
      ("He is learning to cook Chinese dishes.","他在学做中国菜。")]),
    ("eat","吃","动词","食物",
     [("eat out","外出吃饭","We eat out on Fridays."),
      ("eat healthily","健康饮食","You should eat healthily.")],
     [("I usually eat breakfast at seven in the morning.","我通常早上七点吃早餐。"),
      ("She eats too much fast food.","她吃太多快餐了。")]),
    ("drink","喝","动词","食物",
     [("drink water","喝水","I drink water every day.")],
     [("I drink orange juice in the morning.","我早上喝橙汁。"),
      ("You should drink more water in summer.","夏天你应该多喝水。")]),

    # ===== 天气与季节 =====
    ("weather","天气","名词","天气",
     [("the weather","天气","How is the weather?"),
      ("good weather","好天气","We had good weather.")],
     [("The weather is nice today.","今天天气很好。"),
      ("I hope the weather stays sunny.","我希望天气一直晴朗。")]),
    ("sunny","晴朗的","形容词","天气",
     [("a sunny day","晴朗的日子","It is a sunny day.")],
     [("It is sunny today, so we can go out.","今天晴朗，我们可以出去。"),
      ("She likes sunny weather best.","她最喜欢晴天。")]),
    ("rainy","下雨的","形容词","天气",
     [("a rainy day","下雨天","It was a rainy day.")],
     [("It is rainy outside, take an umbrella.","外面下雨，带把伞。"),
      ("I stayed home on the rainy afternoon.","那个下雨的下午我待在家。")]),
    ("hot","热的","形容词","天气",
     [("hot weather","炎热的天气","It is hot in summer.")],
     [("It is very hot in August.","八月非常热。"),
      ("Drink water when it is hot outside.","外面热时要喝水。")]),
    ("cold","冷的","形容词","天气",
     [("cold weather","寒冷的天气","It is cold in winter.")],
     [("It is cold today, so wear a coat.","今天很冷，穿件外套。"),
      ("The water in the lake is cold.","湖里的水很冷。")]),
    ("rain","雨，下雨","名词/动词","天气",
     [("in the rain","在雨中","He walked in the rain."),
      ("rain heavily","下大雨","It rained heavily.")],
     [("It started to rain in the afternoon.","下午开始下雨了。"),
      ("The rain stopped after an hour.","一个小时后雨停了。")]),
    ("snow","雪，下雪","名词/动词","天气",
     [("heavy snow","大雪","There was heavy snow.")],
     [("It snows a lot in the north in winter.","北方冬天常下雪。"),
      ("The children played in the snow.","孩子们在雪里玩。")]),
    ("windy","有风的","形容词","天气",
     [("a windy day","有风的日子","It is a windy day.")],
     [("It is windy here in spring.","这里春天多风。"),
      ("Flying kites is fun on windy days.","有风的日子放风筝很有趣。")]),
    ("cloudy","多云的","形容词","天气",
     [("cloudy sky","多云的天空","The sky is cloudy.")],
     [("It is cloudy but not rainy today.","今天多云但没有下雨。"),
      ("A cloudy day is good for walking.","阴天适合散步。")]),
    ("season","季节","名词","天气",
     [("four seasons","四季","There are four seasons in a year.")],
     [("Spring is my favourite season.","春天是我最喜欢的季节。"),
      ("Each season has its own beauty.","每个季节都有自己的美。")]),
    ("spring","春天","名词","天气",
     [("in spring","在春天","Flowers bloom in spring.")],
     [("The weather gets warm in spring.","春天天气变暖。"),
      ("We plant trees in spring.","我们在春天种树。")]),
    ("summer","夏天","名词","天气",
     [("in summer","在夏天","We swim in summer.")],
     [("I go swimming with friends in summer.","我夏天和朋友去游泳。"),
      ("The days are long in summer.","夏天白天很长。")]),
    ("autumn","秋天","名词","天气",
     [("in autumn","在秋天","Leaves fall in autumn.")],
     [("The leaves turn yellow in autumn.","秋天树叶变黄。"),
      ("Autumn is a cool season.","秋天是个凉爽的季节。")]),
    ("winter","冬天","名词","天气",
     [("in winter","在冬天","It snows in winter.")],
     [("I wear a warm coat in winter.","我冬天穿暖和的外套。"),
      ("Winter in the north is very cold.","北方的冬天非常冷。")]),

    # ===== 健康与身体 =====
    ("health","健康","名词","健康",
     [("good health","健康","Exercise is good for your health.")],
     [("Eating well keeps you in good health.","吃得好让你保持健康。"),
      ("Health is more important than money.","健康比金钱更重要。")]),
    ("healthy","健康的","形容词","健康",
     [("healthy food","健康食物","I eat healthy food."),
      ("stay healthy","保持健康","Do sport to stay healthy.")],
     [("A healthy lifestyle includes exercise.","健康的生活方式包括锻炼。"),
      ("She looks healthy and strong.","她看起来健康又强壮。")]),
    ("body","身体","名词","健康",
     [("your body","你的身体","Exercise your body.")],
     [("Exercise is good for your body and mind.","锻炼对身体和大脑都有好处。"),
      ("He hurt his body in the game.","他在比赛中伤了身体。")]),
    ("sleep","睡觉","名词/动词","健康",
     [("go to sleep","入睡","I go to sleep at ten."),
      ("enough sleep","充足的睡眠","Get enough sleep.")],
     [("I get about eight hours of sleep every night.","我每晚睡大约八小时。"),
      ("Good sleep helps you focus at school.","好的睡眠帮助你在学校集中注意力。")]),
    ("rest","休息","名词/动词","健康",
     [("have a rest","休息一下","Let's have a rest."),
      ("rest well","休息好","Rest well after work.")],
     [("You should rest after a long day of work.","工作一整天后你应该休息。"),
      ("I had a good rest on the weekend.","我周末好好休息了。")]),
    ("doctor","医生","名词","健康",
     [("see a doctor","看医生","You should see a doctor.")],
     [("I went to see a doctor about my cough.","我去看医生看咳嗽。"),
      ("The doctor told me to drink more water.","医生让我多喝水。")]),
    ("medicine","药","名词","健康",
     [("take medicine","吃药","Take medicine after meals.")],
     [("Take this medicine three times a day.","这药一天吃三次。"),
      ("The medicine made me feel better.","这药让我感觉好些了。")]),
    ("ill","生病的","形容词","健康",
     [("be ill","生病","He is ill today.")],
     [("I was ill last week and stayed in bed.","我上周生病卧床。"),
      ("She felt ill after eating too much.","她吃太多后感到不舒服。")]),
    ("tired","疲劳的","形容词","健康",
     [("be tired","累了","I am tired."),
      ("tired of","厌倦","I am tired of waiting.")],
     [("I usually go to the gym after work, but I sometimes go home when I'm tired.","我通常下班后去健身房，但有时累了就直接回家。"),
      ("He felt tired after the long trip.","长途旅行后他感到疲惫。")]),
    ("strong","强壮的","形容词","健康",
     [("strong body","强壮的身体","He has a strong body.")],
     [("Exercise every day makes you strong.","每天锻炼使你强壮。"),
      ("She is strong enough to lift the box.","她强壮得能举起箱子。")]),
    ("energy","精力","名词","健康",
     [("full of energy","充满活力","Children are full of energy.")],
     [("Eating breakfast gives me energy in the morning.","吃早餐让我早上有精力。"),
      ("I have more energy when I sleep well.","睡得好时我精力更充沛。")]),
    ("advice","建议","名词","健康",
     [("give advice","给建议","He gave me good advice."),
      ("take advice","接受建议","I took her advice.")],
     [("The doctor gave me some advice about my health.","医生给了我一些健康建议。"),
      ("Her advice is to exercise every day.","她的建议是每天锻炼。")]),

    # ===== 时间安排与助动词常见词 =====
    ("can","能，可以","情态动词","日常",
     [("can do","能做","I can swim.")],
     [("I can speak a little English.","我会说一点英语。"),
      ("Can you help me with this problem?","你能帮我解决这个问题吗？")]),
    ("should","应该","情态动词","日常",
     [("should do","应该做","You should rest.")],
     [("You should brush your teeth twice a day.","你应该每天刷两次牙。"),
      ("We should protect the environment.","我们应该保护环境。")]),
    ("want","想要","动词","日常",
     [("want to do","想要做","I want to learn English.")],
     [("I want to become a better writer.","我想成为更好的写作者。"),
      ("She wants to visit her aunt this summer.","她今年夏天想去看望阿姨。")]),
    ("need","需要","动词","日常",
     [("need to do","需要做","I need to buy some food.")],
     [("I need to finish this report by Friday.","我需要在周五前完成这份报告。"),
      ("Plants need water and sunlight to grow.","植物生长需要水和阳光。")]),
    ("help","帮助","动词","日常",
     [("help sb with","帮助某人做","She helps me with my homework."),
      ("ask for help","寻求帮助","Don't be afraid to ask for help.")],
     [("I help my mother clean the house on Saturdays.","我周六帮妈妈打扫房子。"),
      ("Can you help me carry these boxes?","你能帮我搬这些箱子吗？")]),
    ("make","制作，使","动词","日常",
     [("make friends","交朋友","It's easy to make friends."),
      ("make a decision","做决定","I made a decision.")],
     [("I make my bed every morning.","我每天早上整理床铺。"),
      ("Music makes me feel happy.","音乐让我感到快乐。")]),
    ("learn","学习","动词","日常",
     [("learn to do","学会做","I learned to cook."),
      ("learn from","向…学习","We learn from our mistakes.")],
     [("I want to learn how to play the guitar.","我想学弹吉他。"),
      ("We learn new words every day.","我们每天学新单词。")]),
    ("know","知道","动词","日常",
     [("know about","了解","I know about that.")],
     [("I know how to ride a bike.","我知道怎么骑自行车。"),
      ("Do you know the way to the museum?","你知道去博物馆的路吗？")]),
    ("think","认为，想","动词","日常",
     [("think about","考虑","I'm thinking about the plan.")],
     [("I think English is very useful.","我认为英语非常有用。"),
      ("Think before you speak.","说话前先想一想。")]),
    ("try","尝试","动词","日常",
     [("try to do","努力做","I try to get up early."),
      ("try doing","试着做","Try exercising more.")],
     [("I will try my best to pass the exam.","我会尽最大努力通过考试。"),
      ("Why not try a new hobby this year?","今年为什么不试试一个新爱好呢？")]),
    ("day","天，日子","名词","时间",
     [("every day","每天","I read every day.")],
     [("I have a busy day at work today.","我今天工作很忙。"),
      ("We play outside on sunny days.","晴天我们在外面玩。")]),
    ("night","夜晚","名词","时间",
     [("at night","在晚上","I read at night.")],
     [("I usually study English after dinner because I have more time at night.","我通常在晚饭后学英语，因为晚上时间更多。"),
      ("The stars are bright at night.","夜晚星星很亮。")]),
]

# 主题映射（阶段0的12周 → 主题）用于预置各周默认词
STAGE0_THEMES = {
    1: "家庭", 2: "日常", 3: "爱好", 4: "日常", 5: "交通",
    6: "日常", 7: "地点", 8: "天气", 9: "食物", 10: "健康",
    11: "日常", 12: "日常",
}


def build_index():
    """从 BASIC_VOCAB 构造查询表: word -> entry"""
    idx = {}
    for (word, meaning, pos, theme, collocs, examples) in V:
        idx[word.lower()] = {
            "word": word, "meaning": meaning, "pos": pos, "theme": theme,
            "collocations": collocs, "examples": examples,
        }
    return idx


INDEX = build_index()


def import_into_db(conn=None):
    """把内置词库写入 dictionary / example_sentences / collocations。幂等。
    可传入已打开的 conn；否则自开新连接。"""
    own = conn is None
    if own:
        init_db()
        conn = get_conn()
    n_words = n_ex = n_co = 0
    try:
        for entry in INDEX.values():
            w = entry["word"].lower()
            conn.execute(
                "INSERT OR IGNORE INTO dictionary (word, meaning, pos, theme) VALUES (?,?,?,?)",
                (w, entry["meaning"], entry["pos"], entry["theme"]))
            n_words += 1
            for (s, t) in entry["examples"]:
                if not s:
                    continue
                conn.execute(
                    "INSERT OR IGNORE INTO example_sentences (word, sentence, translation, grammar_tags, difficulty, source, created_at)"
                    " VALUES (?,?,?,?,?,?,?)",
                    (w, s, t, "", 0, "builtin", ts()))
                n_ex += 1
            for (ph, m, ex) in entry["collocations"]:
                if not ph:
                    continue
                conn.execute(
                    "INSERT OR IGNORE INTO collocations (word, phrase, meaning, example, source) VALUES (?,?,?,?,?)",
                    (w, ph, m, ex or "", "builtin"))
                n_co += 1
        conn.commit()
    finally:
        if own:
            conn.close()
    return {"words": n_words, "examples": n_ex, "collocations": n_co}


if __name__ == "__main__":
    print("导入内置词库:", import_into_db())
